server:
  port: 80

#application 启动时加载数据
application:
   init:redis

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hg?useUnicode=true&characterEncoding=utf8
    username: root
    password: 
  application:
    name: user-manager-service
  #spring -session
  session:
    store-type: redis
  #redis
  redis:
    host: localhost
    port: 6379
    ssl: false
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
    timeout: 30000
    flush-mode: immediate
  mvc:
    static-path-pattern: /**

# Logger Config
logging:
  level:
    com.ql.hg: debug



